- name: Provision Infrastructure
  hosts: localhost
  gather_facts: False
  vars_files:
    - vars.yml
  environment:
    ANSIBLE_HOST_KEY_CHECKING: False

  tasks:
    - name: Install necessary packages on local
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - unzip
        - python3-pip
        - docker.io
        - docker-compose
      become: yes

    - name: Install necessary python packages on local
      pip:
        name: docker-compose
        state: present
        executable: pip3

    - name: Run terraform
      community.general.terraform:
        project_path: "{{ local_terraform_directory }}"
        force_init: true
        state: present
      register: terraform_output

    - name: Parse terraform output
      set_fact:
        server_public_ip: "{{ terraform_output.outputs.server_public_ip.value }}"

    - name: Add new host to inventory
      add_host:
        hostname: "{{ server_public_ip }}"
        groups: webservers


- name: Deploy and Setup Spring Boot app
  hosts: webservers
  gather_facts: no
  vars_files:
    - vars.yml
  become: yes

  tasks:
    - name: Wait for SSH to become available
      wait_for_connection:
        delay: 10
        timeout: 320

    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install necessary packages on remote
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - unzip
        - python3-pip
        - docker.io
        - docker-compose

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started

    - name: Add Docker Group
      group:
        name: docker
        state: present

    - name: Add User to Docker Group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Pull Docker Image from GHCR
      docker_image:
        name: ghcr.io/guithuib/cicd-demo:latest
        source: pull

    - name: Transfer Docker Compose Files
      copy:
        src: ./docker-compose.yaml
        dest: docker-compose.yaml

    - name: Run Docker Compose
      command: docker-compose -f docker-compose.yaml up -d