version: '3'

services:
  db:
    image: 'postgres'
    container_name: scrape-demo
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  build-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp
#    ports:
#      - "8080:8080"


#    depends_on:
#      - db
#    environment:
#      - SPRING.DATASOURCE.URL=jdbc:postgresql://db:5432/postgres
#      - spring.datasource.username=postgres
#      - spring.datasource.password=postgres
#    restart: unless-stopped
