version: '3'

services:
  db:
    image: 'postgres'
    container_name: app-sync
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  build-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
