version: '3'

services:
  db:
    image: 'postgres'
    container_name: scrape-demo
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  myapp:
    image: ghcr.io/guithuib/cicd-demo:latest

#  build-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: myapp

    depends_on:
      - db
    environment:
      - SPRING.DATASOURCE.URL=jdbc:postgresql://db:5432/postgres
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
    restart: unless-stopped
