version: '3'

services:
  db:
    image: 'postgres'
    container_name: scrape-demo
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  myapp:
    image: ghcr.io/guithuib/cicd-demo:latest
    env_file:
      .env
    depends_on:
      - db
    environment:
      - SPRING.DATASOURCE.URL=jdbc:postgresql://db:5432/postgres
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
    restart: unless-stopped







#FROM ubuntu:latest
#
## Install necessary dependencies.
#RUN apt-get update -y \
#    && apt-get install -y \
#    wget \
#    firefox \
#    && apt-get clean
#
## Define the GeckoDriver version you want to install.
#ENV GECKODRIVER_VERSION=0.33.0
#
## Download and install GeckoDriver.
#RUN wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz \
#    && tar -xzf geckodriver-v0.33.0-linux64.tar.gz -C /usr/local/bin/ \
#    && rm geckodriver-v0.33.0-linux64.tar.gz
#
## Set the GeckoDriver executable as executable.
#RUN chmod +x /usr/local/bin/geckodriver
#
## Cleanup to reduce the image size (optional but recommended).
##RUN apt-get autoremove -y \
##    && apt-get clean \
##    && rm -rf /var/lib/apt/lists/*
#
#RUN apt-get install -y openjdk-17-jdk
#RUN apt-get clean && rm -rf /var/lib/apt/lists/*
#ENV MOZ_HEADLESS=1
#WORKDIR /app
#COPY build/libs/*.jar /app/bullhorn-sync.jar
#COPY /src/main/resources/application.properties /app/application.properties
#CMD ["java", "-jar", "bullhorn-sync.jar"]


## Stage 1: Build your application using openjdk:17
#FROM openjdk:17 as builder
#WORKDIR /app
#COPY . /app
##RUN ./gradlew build
#
## Stage 2: Create a smaller image with Firefox
#FROM selenium/standalone-firefox:latest
#ENV MOZ_HEADLESS=1
#WORKDIR /app
#COPY --from=builder /app/build/libs/*.jar /app/bullhorn-sync.jar
#COPY --from=builder /app/src/main/resources/application.properties /app/application.properties
#CMD ["java", "-jar", "bullhorn-sync.jar"]



#FROM ubuntu:latest
#RUN apt-get update \
#    && apt-get remove --purge -y firefox \
#    && apt-get autoremove -y \
#    && apt-get clean
#
#RUN #snap install firefox
#RUN apt-get install -y firefox
#
#RUN apt-get install snapd
#RUN snap install firefox
#
## Install wget (if not already installed)
#RUN apt-get install -y wget
#
## Download GeckoDriver and install it
#RUN wget -O /tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.32.0/geckodriver-v0.32.0-linux64.tar.gz \
#    && tar -xzf /tmp/geckodriver.tar.gz -C /usr/local/bin/ \
#    && rm /tmp/geckodriver.tar.gz
#
## Set executable permissions for GeckoDriver
#RUN chmod +x /usr/local/bin/geckodriver
#
#RUN apt-get install -y openjdk-17-jdk
#RUN apt-get clean && rm -rf /var/lib/apt/lists/*
#ENV MOZ_HEADLESS=1
#WORKDIR /app
#COPY build/libs/*.jar /app/bullhorn-sync.jar
#COPY /src/main/resources/application.properties /app/application.properties
#CMD ["java", "-jar", "bullhorn-sync.jar"]



## Use an official OpenJDK runtime as a parent image
#FROM openjdk:17
#
## Set the working directory in the container
#WORKDIR /app
#
## Copy the Gradle build files and dependencies to the container
#COPY build/libs/*.jar /app/bullhorn-sync.jar
#COPY /src/main/resources/application.properties /app/application.properties
#
## Define the command to run your Spring Boot application
#CMD ["java", "-jar", "bullhorn-sync.jar"]