name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  #First we will see the application build or not , then we will deploy in EC2
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build

      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: Package
          path: build/libs


          #      - name: Upload JAR artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: my-app-artifact
#          path: /build/libs/**.jar
#
#      - name: Download JAR artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: my-app-artifact
#          path: /build/libs/**.jar
          

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY  }}
          HOSTNAME : 35.174.101.105
          USER_NAME : ${{ secrets.USER_NAME  }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@35.174.101.105
          scp -o StrictHostKeyChecking=no -i private_key build/libs/**.jar ubuntu@35.174.101.105:build/libs/

          docker-compose -f docker-compose.yaml up -d --build
          
          

#jobs:
#  build:
#    runs-on: ubuntu-latest
#


#               scp -o StrictHostKeyChecking=no -i private_key "${{ github.workspace }}/build/libs/scrape-demo.jar" ubuntu@35.174.101.105:/build/libs/

#      - name: Build the docker_compose
#        run: docker-compose up -d --build


#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#
#      - name: Make gradlew executable
#        run: chmod +x gradlew
#
#      - name: Build with Gradle
#        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
#        with:
#          arguments: build
#
#      - name: Set up SSH key
#        run: |
#          mkdir -p ~/.ssh || true
#          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ryan-demo.pem
#          chmod 600 ~/.ssh/ryan-demo.pem
#          ssh-keygen -y -f ~/.ssh/ryan-demo.pem > ~/.ssh/id_rsa
#          ssh-keyscan -H  35.174.101.105 >> ~/.ssh/known_hosts
#        env:
#          SSH_AUTH_SOCK: /tmp/ssh_agent.sock


#      - name: Set up SSH
#        uses: webfactory/ssh-agent@v0.7.0
#        with:
#          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

#      - name: SSH into EC2 and copy JAR file
#        run: |
#          ssh -o StrictHostKeyChecking=no -i ${{ runner.workspace }}/${{ secrets.EC2_SSH_KEY }} ec2-user@YOUR_EC2_PUBLIC_IP 'mkdir -p ./build'
#          scp -i ${{ runner.workspace }}/${{ secrets.EC2_SSH_KEY }} ./build.jar ec2-user@YOUR_EC2_PUBLIC_IP:/path/on/ec2/




#      - name: Set up SSH key
#        run: |
#          mkdir -p ~/.ssh
#          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/your-ec2-key.pem
#          chmod 600 ~/.ssh/your-ec2-key.pem
#          ssh-keygen -y -f ~/.ssh/your-ec2-key.pem > ~/.ssh/id_rsa
#          ssh-keyscan -H your-ec2-instance-ip >> ~/.ssh/known_hosts
#        env:
#          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
#
#      - name: Copy JAR file
#        run: scp -i ~/.ssh/your-ec2-key.pem path/to/your.jar ec2-user@your-ec2-instance-ip:/path/on/ec2/



#      - name: Install Dependencies
#        run: pip install ansible
#
#      - name: Run Ansible Playbook
#        run: ansible-playbook deployment.yml


#  EC2-Deploy:
#    runs-on: ubuntu-latest
#    environment:
#      name: ${{ github.ref_name }}
#      url: 3.210.104.127
#    steps:
#      - id: deploy
#        name: Deploy
#        uses: bitovi/github-actions-deploy-docker-to-ec2@v0.5.0
#        with:
#          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID}}
#          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
#          aws_default_region: us-east-1
